export const WORD_BAN_LIST: { [key: string]: string } = {
  will: "future tense",
  had: "past tense",
  has: "past tense",
  was: "past tense",
  by: "passive voice?",
  being: "passive voice?",
  gets: "passive voice?",
  "are used to": "CCG: remove",
  "has been": "CCG: replace with is or remove",
  "has finished": "CCG: replace with is done / is complete",
  "has the option of": "CCG: replace with can",
  "have finished": "CCG: replace with are done",
  "have the ability to": "CCG: replace with can",
  "if you want to": "CCG: replace with to",
  "in order to": "CCG: replace with to",
  "is able to": "CCG: replace with can",
  "is designed to": "CCG: remove",
  "offers the ability to": "CCG: replace with lets you",
  "once": "CCG: replace with one time / after",
  "since": "CCG: replace with because / after",
  "will also be able to": "CCG: replace with can also",
  "will be": "CCG: replace with is / are or remove",
  "will be able to": "CCG: remove",
  "will have been": "CCG: replace with is / are",
  "will have the ability to": "CCG: replace with can",
  "will have to": "CCG: replace with must",
  "will have to be": "CCG: replace with must be",
  "will then be": "CCG: replace with are / is",
  "without the need to access": "CCG: replace with without accessing",
  "would be": "CCG: replace with are / is",
  "would like": "CCG: replace with want",
};
